server:
  port: 9999
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream 
spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://localhost:9411/
zuul:
  routes:
    user:
      path: /user/**
      url: http://localhost:9998/auth-service/uaa/user
security:
  oauth2:
    sso:
      home:
        secure: false
        path: /,/**/*.html
    client:
      accessTokenUri: http://localhost:9998/auth-service/uaa/oauth/token
      userAuthorizationUri: http://localhost:9998/auth-service/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      userInfoUri: http://localhost:9998/auth-service/uaa/user
