server:
  port: 9999
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: thread
          thread:
            timeoutInMilliseconds: 15000      
spring:
  sleuth:
    sampler:
      percentage: 1.0
