server:
  port: 8765
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream 
spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://localhost:9411/
zuul:
  routes:
    user:
      path: /user/**
      url: http://localhost:9999/uaa/user
    uaa:
      sensitiveHeaders: Authorization
      path: /uaa/**
      stripPrefix: false
security:
  user:
    password: password
  oauth2:
    client:
      scope: read, write
      authorizedGrantTypes: authorization_code,refresh_token,password
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      userInfoUri: http://localhost:9999/uaa/user
