server:
  port: 9999
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream 
spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://localhost:9411/
